### ISSUE TITLE
netcat Package

### ISSUE THREAD

**Issue by adschm** [rohammer/Simple-Babelweb#14]
Ich hatte gerade viel Spaß, bis ich herausgefunden habe, dass ich netcat-openbsd brauche. Bitte in die README aufnehmen:

apt-get -y remove netcat-traditional netcat
apt-get -y install netcat-openbsd

Sonst nix IPv6 und damit nur eine hängende Seite ohne jede Ausgabe.

**Comment by rohammer** [comment]
Erledigt
