### ISSUE TITLE
Anfragen nicht limitiert, babeld DoS möglich

### ISSUE THREAD

**Issue by fblaese** [rohammer/Simple-Babelweb#16]
Durch vielfach paralleles aufrufen der Seite wird babeld durch den vielen Output auf dem local-port überlastet, verliert Verbindungen.

Eine mögliche Lösung wäre das Begrenzen der Anfragen, eine weitere wäre, das Problem im babeld zu fixen.

**Comment by rohammer** [comment]
fixed!
